# Generated by Django 4.2 on 2024-10-04 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_position_options_and_more'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ('name',), 'verbose_name': 'Компетенция', 'verbose_name_plural': 'Компетенции'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('name',), 'verbose_name': 'Домен', 'verbose_name_plural': 'Домены'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',), 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название компетенции'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название навыка'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(verbose_name='Дата оценки')),
                ('rating_value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка сотрудника')),
                ('suitability', models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('не требуется', 'Не требуется')], default='не требуется', max_length=12, verbose_name='Соответствие')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.skill', verbose_name='Оцениваемый навык')),
            ],
            options={
                'verbose_name': 'Оценка навыков сотрудника',
                'verbose_name_plural': 'Оценки навыков сотрудников',
                'ordering': ('employee__last_name', 'employee__first_name', '-rating_date'),
                'default_related_name': 'ratings',
            },
        ),
    ]
