# Generated by Django 4.2 on 2024-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_competence_options_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'default_related_name': 'ratings', 'ordering': ('employee__last_name', 'employee__first_name'), 'verbose_name': 'Оценка навыков сотрудника', 'verbose_name_plural': 'Оценки навыков сотрудников'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='suitability',
            field=models.CharField(choices=[('да', 'Да'), ('нет', 'Нет'), ('не требуется', 'Не требуется')], default='не требуется', max_length=12, verbose_name='Соответствие'),
        ),
    ]
