# Generated by Django 4.2 on 2024-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_rating_options_alter_rating_suitability'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('rating_date', 'skill', 'employee'), name='unique_employee_skill_rating_on_date', violation_error_message='Оценка навыка на выбранную дату по данному сотруднику уже есть!'),
        ),
    ]
