# Generated by Django 4.2 on 2024-10-14 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_employee_first_name', message='Введены недопустимые символы.', regex='^[а-яА-ЯёЁa-zA-Z]+(\\s?\\-?[а-яА-ЯёЁa-zA-Z]+){0,5}$'), django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_employee_last_name', message='Введены недопустимые символы.', regex='^[а-яА-ЯёЁa-zA-Z]+(\\s?\\-?[а-яА-ЯёЁa-zA-Z]+){0,5}$'), django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Фамилия сотрудника'),
        ),
    ]
