# Generated by Django 4.2 on 2025-01-12 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_first_name_alter_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_employee_first_name', message='Введены недопустимые символы.', regex='^[а-яА-ЯёЁa-zA-Z]+(\\s?\\-?[а-яА-ЯёЁa-zA-Z]+){0,5}$'), django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_employee_last_name', message='Введены недопустимые символы.', regex='^[а-яА-ЯёЁa-zA-Z]+(\\s?\\-?[а-яА-ЯёЁa-zA-Z]+){0,5}$'), django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Фамилия сотрудника'),
        ),
    ]
