# Generated by Django 4.2 on 2025-01-16 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_full_name_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_employee_first_name', message='Введены недопустимые символы.', regex='^[А-ЯЁа-яёA-Za-z]+(?:[\\s\\-]?[А-ЯЁа-яёA-Za-z]+)*$'), django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_employee_last_name', message='Введены недопустимые символы.', regex='^[А-ЯЁа-яёA-Za-z]+(?:[\\s\\-]?[А-ЯЁа-яёA-Za-z]+)*$'), django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Фамилия сотрудника'),
        ),
    ]
