version: '3'

volumes:
  dashboard_data:
  static:

services:
  db:
    image: postgres:14.9-alpine3.18
    env_file: ../../.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - dashboard_data:/var/lib/postgresql/data
  backend:
    image: dashboard
    env_file: ../../.env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  nginx_dashboard:
    image: nginx:1.25.3-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles/
    depends_on:
      - backend